# This is a basic workflow to help you get started with Actions

name: Test deployment via SSH

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [  ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM
        uses: fifsky/ssh-action@master
        with:
          command: |
            git pull origin
          host: ${{ secrets.SSH_HOST }}
          user: elijaho
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          args: "-vvv"
