# This is a basic workflow to help you get started with Actions

name: Deployment via SSH

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ production ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM
        uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf leyline-discord/
            git clone -b production --single-branch git@github.com:Leyline-gg/leyline-discord.git
            cd leyline-discord/
            npm install
            pm2 delete all
            npm run deploy
          host: ${{ secrets.SSH_HOST }}
          user: github-actions
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          args: "-vvv"
