name: Production deployment via SSH

on:
    push:
        branches: [production]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: SSH into VM
              uses: fifsky/ssh-action@master
              with:
                  command: |
                      cd leyline-discord
                      git checkout production
                      git reset --hard origin/production
                      git pull
                      npm ci
                      pm2 delete all
                      npm run deploy
                  host: ${{ secrets.SSH_HOST }}
                  user: github-actions
                  key: ${{ secrets.SSH_PRIVATE_KEY}}
                  args: '-vvv'
